use_frameworks!

platform :ios, '8.0'

target 'LEGONavigationController_Example' do
  pod 'LEGONavigationController', :path => '../'

  target 'LEGONavigationController_Tests' do
    inherit! :search_paths

    
  end
end
